### PR TITLE
Client.Capture: Return closed chan for nil clients.

### LINKED ISSUE #129: Client.Capture: Should return a closed chan, not a nil chan
Stripe Veneur has code like the following to ensure that in the case of fatal errors, sentry receives the message:

```go
	_, ch := ravenClient.Capture(&p, nil)

	if e.Level == logrus.PanicLevel || e.Level == logrus.FatalLevel {
		// we don't want the program to terminate before reporting to sentry
		return <-ch
	}
```

If Sentry is not configured, Veneur relies on the fact that "It is a no-op when client is nil." (from the Capture API doc). Unfortunately, the implementation returns a `nil` channel. Reading from a `nil` channel blocks forever. This hangs the server when it is trying to crash. Instead, Capture should return a *closed* channel, which will always return nil.

As a workaround, I'm modifying Veneur to not call the Client.Capture if the client is nil.

### PR DESCRIPTION
**Pull request by evanj**
The API docs state that Capture "is a no-op when client is nil." This
suggests that there should be no errors when calling it, so receiving
an error from the error chan result should immediately return nil.
Previously, it would return a nil chan. Receiving from a nil chan
blocks forever, which caused callers to need to check for nil clients
in some cases.

Change Capture to return a closed chan for nil clients, which will
immediately return nil. Fixes #129.

### CODE REVIEW

File: client.go [hunk 1]
```diff
@@ -495,7 +503,10 @@ func (client *Client) worker() {
 // send's success.
 func (client *Client) Capture(packet *Packet, captureTags map[string]string) (eventID string, ch chan error) {
 	if client == nil {
```
Comment (mattrobenolt) [inline client.go]: Why are we duplicating this `if` statement?

File: client.go [hunk 2]
```diff
@@ -52,6 +52,14 @@ const (
 
 type Timestamp time.Time
 
+// return by Capture for nil clients
+var closedChan chan error
```
Comment (mattrobenolt) [inline client.go]: I get that you're trying to reuse one single object for every case, but I think I'd rather create a unique closed channel for each call. Especially since, in theory, this should be getting used less often. So for the cases where we don't need it, we're allocating unnecessary memory.

File: client.go (hunk 1 above)
Comment (evanj) [inline client.go]: Oops sorry, this was a weird copy-and-paste issue; clearly I didn't review my own commit oops

File: client.go (hunk 2 above)
Comment (evanj) [inline client.go]: Sure, that's fine with me. Arguably since the "normal" code path also allocates a channel, this won't really be any different.

File: client.go [hunk 3]
```diff
@@ -494,7 +494,11 @@ func (client *Client) worker() {
 // when client is nil. A channel is provided if it is important to check for a
 // send's success.
 func (client *Client) Capture(packet *Packet, captureTags map[string]string) (eventID string, ch chan error) {
+	ch = make(chan error, 1)
+
 	if client == nil {
+		// return a chan that always returns nil when the caller receives from it
```
Comment (mattrobenolt) [inline client.go]: This comment is now inaccurate. :)

Comment (evanj) [inline client.go]: How so? The channel is closed, so it will always return nil. That is what `TestNilClient` is verifying. Did I screw something up?

Comment (mattrobenolt) [inline client.go]: Oh, my b. I misread it as "always return nil".

Looks like we're good.

**Comment by mattrobenolt** [comment]
Thanks! 🍦

**Comment by evanj** [comment]
Who hoo thank you!
